name: Build AddressablesTools Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Build AddressablesTools
      run: msbuild AddressablesTools.sln /restore /p:Configuration=Release
    
    - name: Restore NuGet packages
      run: msbuild /t:restore
      
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: AddressablesTools-windows
        path: AddressablesTools/bin/Release/net6.0